// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_password)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type CreateUserParams struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Email,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const getUserByEmailLogin = `-- name: GetUserByEmailLogin :one
select id, created_at, updated_at, email, hashed_password, is_chirpy_red
from users
where email = $1
`

func (q *Queries) GetUserByEmailLogin(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailLogin, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const resetAllUsers = `-- name: ResetAllUsers :exec
delete from users
`

func (q *Queries) ResetAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAllUsers)
	return err
}

const ugradeUserRedChirp = `-- name: UgradeUserRedChirp :one
update users
set is_chirpy_red = true
where id = $1
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

func (q *Queries) UgradeUserRedChirp(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, ugradeUserRedChirp, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const updateUserHashedPasswordOrEmail = `-- name: UpdateUserHashedPasswordOrEmail :one
update users
set hashed_password = $1, email = $2, updated_at =$3
where id = $4
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type UpdateUserHashedPasswordOrEmailParams struct {
	HashedPassword string
	Email          string
	UpdatedAt      time.Time
	ID             uuid.UUID
}

func (q *Queries) UpdateUserHashedPasswordOrEmail(ctx context.Context, arg UpdateUserHashedPasswordOrEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserHashedPasswordOrEmail,
		arg.HashedPassword,
		arg.Email,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
